### ISSUE TITLE
npm install external library failed

### ISSUE THREAD

**Issue by sskyy** [skpm/skpm#99] opened 2017-12-14 06:13 UTC
I use `npm install` to install some external node package but got:

```
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/sketch-polyfill-setinterval
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_strip-ansi@4.0.0@strip-ansi/node_modules/ansi-regex
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/yesno
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/acorn
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/ajv-keywords
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/ansi-styles
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/author-regex
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/parse-author
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/babel-preset-env
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/babel-preset-react
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/cocoascript-class
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/sketch-polyfill-fetch
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/coscript
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/run-sketch-plugin
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/enhanced-resolve
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/escape-string-regexp
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/find-cache-dir
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/fsevents
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/has-ansi/node_modules/ansi-regex
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/has-ansi
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/interpret
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/json-loader
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/loader-runner
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/loader-utils
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/loose-envify
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/node-libs-browser
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/webpack
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/object.assign
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/babel-preset-airbnb
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/babel-preset-airbnb
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/parse-author
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/run-sketch-plugin
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/schema-utils
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/sketch-polyfill-fetch
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/sketch-polyfill-setinterval
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/slash
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/webpack
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/yesno
npm WARN checkPermissions Missing write access to /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/has-ansi/node_modules
npm WARN my-test-sketch@0.1.0 No repository field.
npm WARN my-test-sketch@0.1.0 No license field.

npm ERR! path /Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/sketch-polyfill-setinterval
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/jiamiu/Documents/work/personal/my-test-sketch/node_modules/_@skpm_builder@0.2.4@@skpm/builder/node_modules/sketch-polyfill-setinterval'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

My skpm and npm version are:

```
 skpm --version
1.0.12

npm --version
5.5.1
```

Couldn't find a solution, please help. Thank you.

**Comment by mathieudutour** [comment] 2017-12-14 12:07
hum did you perhaps use npm with `sudo` or something? seems like your set up is messed up: you don't have the rights to access your own files.

I'm going to close this since it's not a bug in skpm

**Closed by mathieudutour** 2017-12-14 12:07 UTC
