### ISSUE TITLE
Running sketchtool from inside skpm plugin causes kernel panic

### ISSUE THREAD

**Issue by thibmaek** [skpm/skpm#188] opened 2018-10-22 13:49 UTC
In a plugin trying to do:

```
const absolutePath = sketch.fromNative(context.document).path;

execSync(`/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export slices ${absolutePath} --output ~/Desktop/ --format="png" --scales="1, 2, 3"`);
```

caused my laptop to freeze after 2 minutes when the plugin was in watch mode with npm start and then dimmed my screen, and caused a kernel panic.

Just before the panic I opened terminal and immediately got a bash warning: bash using to much resources on same file.

**Comment by mathieudutour** [comment] 2018-10-22 15:55
duplicate of #189

**Closed by mathieudutour** 2018-10-22 15:55 UTC
