### ISSUE TITLE
Question: is there a way to use node `fs` within a plugin?

### ISSUE THREAD

**Issue by timohofmeijer** [skpm/skpm#36] opened 2017-04-24 10:33 UTC
I’m experimenting with a plugin which uses `JSZip` to manipulate a `.sketch` file. For this I’m using a node script which I am now trying to run as a plugin. In order to hand  `JSZip` a sketch file,  I’m using `fs`, `require(''fs')` makes `skpm build` throw errors about not being able to resolve `fs`. Is there a way to access the file system from within  a Sketch plugin?

**Comment by mathieudutour** [comment] 2017-04-24 10:43
you can't use `fs` directly because it's a node package and sketch plugins doesn't run on node. That being said, there is a way to access the file system using the NSFoundation APIs: NSFileManager, NSString.stringWithContentsOfFile_encoding_error, etc.

I started creating a package to polyfill the fs package on sketch: https://github.com/mathieudutour/sketch-module-fs but i was too lazy to do it entirely. If you want to contribute to it and if we manage to have a complete polyfill, we could include it automatically in skpm (like `fetch` and `console` here: https://github.com/sketch-pm/skpm/pull/35

**Comment by mathieudutour** [comment] 2017-06-02 13:06
Going to close this but feel free to ping me if you get the change to implement a polypill

**Closed by mathieudutour** 2017-06-02 13:06 UTC
Labels: help wanted, question

**Comment by abbrechen** [comment] 2019-02-14 14:01
Is it part of skpm now or how to use the sketch-module-fs?

**Comment by mathieudutour** [comment] 2019-02-14 14:03
not part of skpm no, you need to install it separately: `npm install @skpm/fs`

**Comment by abbrechen** [comment] 2019-02-15 13:52
Thanks a lot.

**Comment by narendrasinghrathore** [comment] 2020-08-28 12:46
Module not found: Error: Can't resolve 'fs'

**Comment by mathieudutour** [comment] 2020-08-28 13:15
Have you read the previous comments?

**Comment by narendrasinghrathore** [comment] 2020-08-28 13:46
Yes, @mathieudutour I did.
But the issue is, I am using a node module which eventually depends on multiple node modules.
So I think It's not a feasible solution to manually update all imports
``` 
   const fs  = require('fs')

   to

   import * as fs from '@skpm/fs'
```
Can you please share something more generic, because there can be the case where the one dependent node module in our app internally depends on multiple node modules which depends on 'fs'?

```
 inception 🤯
```

Please let me know if I missed something.

Thanks

**Comment by mathieudutour** [comment] 2020-08-28 13:55
Please write a comment like that the first time next time 🙂 

You don't have to manually update all imports, you can tell webpack to do it for you https://webpack.js.org/configuration/resolve/

That being said, `@skpm/fs` only implements the synchronous API so depending on thee modules you are using, it might still not work.

**Comment by narendrasinghrathore** [comment] 2020-08-28 14:04
@mathieudutour thanks for quick response, can you suggest some alternative to this.

**Comment by mathieudutour** [comment] 2020-08-28 14:09
Use another module?

**Comment by narendrasinghrathore** [comment] 2020-08-28 14:42
![giphy](https://user-images.githubusercontent.com/4208015/91580286-7c556d80-e96a-11ea-8dce-892e39d04a6c.gif)
@mathieudutour

**Comment by mathieudutour** [comment] 2020-08-28 15:01
That's not a joke. There isn't any other fs polyfill for Sketch as far as I know. So if you can't use this one, you will need to find a workaround which might be to use a module that doesn't need fs
