### ISSUE TITLE
SKPM log -f does not tail anymore but quits.

### ISSUE THREAD

**Issue by happylinks** [skpm/skpm#187] opened 2018-10-12 12:57 UTC
Title says it all, skpm log -f returns exit code 0, while I think it should tail.

**Comment by mathieudutour** [comment] 2018-10-12 15:38
Hum interesting, same as https://github.com/skpm/skpm/issues/186 🤔 

I can't reproduce tho

**Comment by happylinks** [comment] 2018-10-12 15:53
Ahh weird, for me it’s consistent. I’ll try some other environments to see if I can figure out what might be wrong.

**Comment by mathieudutour** [comment] 2018-10-15 07:04
Fixed in https://github.com/skpm/skpm/commit/d4406a599a5cb1b3fc786c562153e7b2d5555dcd

**Closed by mathieudutour** 2018-10-15 07:04 UTC
Labels: bug

**Comment by happylinks** [comment] 2018-10-15 07:39
Greattt, thanks!

**Comment by smlparry** [comment] 2018-10-15 23:48
This is still happening for me using skpm 1.1.9
<img width="398" alt="screen shot 2018-10-15 at 6 36 25 pm" src="https://user-images.githubusercontent.com/7920702/46984224-c8b29f80-d0a9-11e8-931a-230299168729.png">

I am running OSX 10.14 Mojave if that could be the issue?
<img width="202" alt="screen shot 2018-10-15 at 6 47 54 pm" src="https://user-images.githubusercontent.com/7920702/46984436-e2a0b200-d0aa-11e8-9196-5f6d7ff57276.png">
