### ISSUE TITLE
onRun handler not found in Sketch 49

### ISSUE THREAD

**Issue by wwsun** [skpm/skpm#135] opened 2018-03-19 07:58 UTC
this issue is similar with #49 

after run `npm run watch`. For first time, it works good, however, when change some codes, and reload the plugin via "Sketch Preferences", the plugin crashed and logs:

```
... does not contain a handler function named: onRun.
```

Restart Sketch, the plugin works good again. Reload plugin will crash again.

manifest is

```
    {
      "name": "Toolbar",
      "description": "Show Toolbar",
      "identifier": "foo.bar.show-toolbar",
      "script": "./show-toolbar.js"
    },
```

and the build codes is following

```js
var that = this;
function __skpm_run (key, context) {
  that.context = context;

var exports =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports) {

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports['default'] = function (context) {
  context.document.showMessage('hello sketch');
};

/***/ })
/******/ ]);
  if (key === 'default' && typeof exports === 'function') {
    exports(context);
  } else {
    exports[key](context);
  }
}
that['onRun'] = __skpm_run.bind(this, 'default')
```

**Comment by mathieudutour** [comment] 2018-03-20 08:23
how do you "reload the plugin via "Sketch Preferences""?

**Comment by wwsun** [comment] 2018-03-21 02:00
1. Sketch > Plugins -> Manage Plugins
2. Unselect the plugin
3. Select the plugin

**Comment by mathieudutour** [comment] 2018-03-21 06:41
I see. There seems to be a bug when you disable a plugin: http://sketchplugins.com/d/668-can-t-run-plugin-after-disabling-other-plugins

This is not a bug in `skpm` tho so I'll close this issue. (you should activate the dev mode instead of disabling/re-enabling your plugin everytime: https://developer.sketchapp.com/guides/preferences/#always-reload-scripts-before-running)

**Closed by mathieudutour** 2018-03-21 06:41 UTC
